// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: user.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Course        string                 `protobuf:"bytes,3,opt,name=course,proto3" json:"course,omitempty"`
	Faculty       string                 `protobuf:"bytes,4,opt,name=faculty,proto3" json:"faculty,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetCourse() string {
	if x != nil {
		return x.Course
	}
	return ""
}

func (x *User) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"`
	FirstName     *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	Course        *string                `protobuf:"bytes,3,opt,name=course,proto3,oneof" json:"course,omitempty"`
	Faculty       *string                `protobuf:"bytes,4,opt,name=faculty,proto3,oneof" json:"faculty,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdate) Reset() {
	*x = UserUpdate{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdate) ProtoMessage() {}

func (x *UserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdate.ProtoReflect.Descriptor instead.
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserUpdate) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UserUpdate) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UserUpdate) GetCourse() string {
	if x != nil && x.Course != nil {
		return *x.Course
	}
	return ""
}

func (x *UserUpdate) GetFaculty() string {
	if x != nil && x.Faculty != nil {
		return *x.Faculty
	}
	return ""
}

func (x *UserUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGet) Reset() {
	*x = UserGet{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGet) ProtoMessage() {}

func (x *UserGet) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGet.ProtoReflect.Descriptor instead.
func (*UserGet) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserGet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDelete) Reset() {
	*x = UserDelete{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelete) ProtoMessage() {}

func (x *UserDelete) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelete.ProtoReflect.Descriptor instead.
func (*UserDelete) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserDelete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuthCheckModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCheckModel) Reset() {
	*x = AuthCheckModel{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCheckModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCheckModel) ProtoMessage() {}

func (x *AuthCheckModel) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCheckModel.ProtoReflect.Descriptor instead.
func (*AuthCheckModel) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *AuthCheckModel) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bbuf/validate/validate.proto\"\xbd\x01\n" +
	"\x04User\x12&\n" +
	"\busername\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01R\busername\x12)\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01R\tfirstName\x12\"\n" +
	"\x06course\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01R\x06course\x12$\n" +
	"\afaculty\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01R\afaculty\x12\x18\n" +
	"\x02id\x18\x05 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x8a\x02\n" +
	"\n" +
	"UserUpdate\x12+\n" +
	"\busername\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01H\x00R\busername\x88\x01\x01\x12.\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01H\x01R\tfirstName\x88\x01\x01\x12'\n" +
	"\x06course\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01H\x02R\x06course\x88\x01\x01\x12)\n" +
	"\afaculty\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01H\x03R\afaculty\x88\x01\x01\x12\x18\n" +
	"\x02id\x18\x05 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02idB\v\n" +
	"\t_usernameB\r\n" +
	"\v_first_nameB\t\n" +
	"\a_courseB\n" +
	"\n" +
	"\b_faculty\"#\n" +
	"\aUserGet\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"&\n" +
	"\n" +
	"UserDelete\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"/\n" +
	"\x0eAuthCheckModel\x12\x1d\n" +
	"\x04code\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\bR\x04code\"\x1d\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xd4\x01\n" +
	"\x04Crud\x12<\n" +
	"\x0eDeleteUserByID\x12\x10.user.UserDelete\x1a\x16.google.protobuf.Empty\"\x00\x120\n" +
	"\x0eUpdateUserByID\x12\x10.user.UserUpdate\x1a\n" +
	".user.User\"\x00\x12*\n" +
	"\vGetUserByID\x12\r.user.UserGet\x1a\n" +
	".user.User\"\x00\x120\n" +
	"\tCheckAuth\x12\x14.user.AuthCheckModel\x1a\v.user.Token\"\x00B)Z'github.com/project-misis/users_proto/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_proto_goTypes = []any{
	(*User)(nil),           // 0: user.User
	(*UserUpdate)(nil),     // 1: user.UserUpdate
	(*UserGet)(nil),        // 2: user.UserGet
	(*UserDelete)(nil),     // 3: user.UserDelete
	(*AuthCheckModel)(nil), // 4: user.AuthCheckModel
	(*Token)(nil),          // 5: user.Token
	(*emptypb.Empty)(nil),  // 6: google.protobuf.Empty
}
var file_user_proto_depIdxs = []int32{
	3, // 0: user.Crud.DeleteUserByID:input_type -> user.UserDelete
	1, // 1: user.Crud.UpdateUserByID:input_type -> user.UserUpdate
	2, // 2: user.Crud.GetUserByID:input_type -> user.UserGet
	4, // 3: user.Crud.CheckAuth:input_type -> user.AuthCheckModel
	6, // 4: user.Crud.DeleteUserByID:output_type -> google.protobuf.Empty
	0, // 5: user.Crud.UpdateUserByID:output_type -> user.User
	0, // 6: user.Crud.GetUserByID:output_type -> user.User
	5, // 7: user.Crud.CheckAuth:output_type -> user.Token
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
